version: "3.9"

services:
  app:
    build: .
    container_name: crm-backend
    env_file:
      - ./src/.env.example
      - ./.env
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
      - RATE_LIMIT_ANALYZE=${RATE_LIMIT_ANALYZE}
      - TOKEN_COST_PER_TEXT=${TOKEN_COST_PER_TEXT}
      - TOKEN_COST_PER_IMAGE=${TOKEN_COST_PER_IMAGE}
      - OPENAI_TIMEOUT_SECONDS=${OPENAI_TIMEOUT_SECONDS}
    volumes:
      - ./logs:/logs
      - ./.env:/.env:ro
    expose:
      - "8080"
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: crm-nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - web

  certbot:
    image: certbot/certbot:latest
    container_name: crm-certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM; while :; do \
      certbot renew --noninteractive --webroot -w /usr/share/nginx/html; \
      sleep 12h; \
      done"

  certbot_init:
    image: certbot/certbot:latest
    container_name: crm-certbot-init
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL_FOR_CERTBOT=${EMAIL_FOR_CERTBOT}
    volumes:
      - ./certs:/etc/letsencrypt
      - ./frontend/dist:/usr/share/nginx/html
    entrypoint: /bin/sh -c
    command: >
      "if [ ! -f /etc/letsencrypt/live/${DOMAIN}/fullchain.pem ]; then \
        certbot certonly --noninteractive --agree-tos --email ${EMAIL_FOR_CERTBOT} \
          --webroot -w /usr/share/nginx/html -d ${DOMAIN}; \
      else \
        echo 'Certs exist for ${DOMAIN}, skipping init'; \
      fi"

networks:
  web:
    driver: bridge
