version: '3.8'

services:
  backend:
    build: ./backend
    container_name: salesvision-backend
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build: ./nginx
    container_name: salesvision-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx:/nginx-src
    environment:
      - DOMAIN=${DOMAIN}
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: salesvision-frontend
    environment:
      - VITE_APP_NAME=${VITE_APP_NAME}
      - VITE_FRONTEND_URL=${VITE_FRONTEND_URL}
      - VITE_DEFAULT_LOCALE=${VITE_DEFAULT_LOCALE}
      - VITE_SUPPORTED_LOCALES=${VITE_SUPPORTED_LOCALES}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  # Optional: Add a database service if not using Supabase
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: salesvision-postgres
  #   environment:
  #     - POSTGRES_DB=salesvision
  #     - POSTGRES_USER=salesvision
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

volumes:
  postgres_data:

