import { useState } from 'react'
import { motion } from 'framer-motion'
import { Download, FileText, Loader } from 'lucide-react'
import toast from 'react-hot-toast'

const ExportButton = ({ chartData, insights, user }) => {
  const [isExporting, setIsExporting] = useState(false)

  const generateReportContent = () => {
    const currentDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })

    return `
# SalesVision XAI-360 Analytics Report
Generated on ${currentDate}

## Executive Summary

This report contains comprehensive analytics insights from your multimodal sales data analysis.

### Key Metrics
- Total Sales: $2.4M (+8.3%)
- Sentiment Score: 0.78 (Positive)
- Average Brightness: 62% (+12%)
- Forecast Accuracy: 91% (+3.2%)

### AI Insights Summary

${insights.map(insight => `- ${insight.text}`).join('\n')}

### Chart Analysis

#### Sales Performance
The sales performance chart shows strong upward trajectory with seasonal patterns. Recent data indicates consistent growth with forecast accuracy maintaining 91% reliability.

#### Sentiment Analysis
Customer sentiment analysis reveals positive engagement levels with emotional responses driving higher conversion rates. Sentiment scores correlate with retention rates.

#### Visual Impact
Visual element analysis demonstrates how image characteristics and brightness levels influence customer perception. Bright, vibrant visuals generate higher engagement rates.

#### Correlation Analysis
Multi-modal correlation analysis reveals strong relationships between sales performance, sentiment scores, and visual marketing elements.

### Recommendations

1. Continue leveraging positive sentiment trends
2. Optimize visual brightness for maximum engagement
3. Maintain forecast accuracy through data quality
4. Focus on integrated multi-modal strategies

---
Report generated by SalesVision XAI-360
Powered by Asenay Tech
    `.trim()
  }

  const exportToPDF = async () => {
    setIsExporting(true)
    
    try {
      // Simulate PDF generation
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      // Create a blob with the report content
      const content = generateReportContent()
      const blob = new Blob([content], { type: 'text/plain' })
      
      // Create download link
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `SalesVision-XAI-360-Report-${new Date().toISOString().split('T')[0]}.txt`
      
      // Trigger download
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      
      // Clean up
      URL.revokeObjectURL(url)
      
      toast.success('Report exported successfully!')
    } catch (error) {
      toast.error('Export failed. Please try again.')
    } finally {
      setIsExporting(false)
    }
  }

  return (
    <motion.button
      whileHover={{ scale: 1.05 }}
      whileTap={{ scale: 0.95 }}
      onClick={exportToPDF}
      disabled={isExporting}
      className="flex items-center space-x-2 px-4 py-2 bg-gradient-accent text-white rounded-lg font-medium disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-neon-blue transition-all duration-300"
    >
      {isExporting ? (
        <>
          <Loader className="h-4 w-4 animate-spin" />
          <span>Exporting...</span>
        </>
      ) : (
        <>
          <Download className="h-4 w-4" />
          <span>Export Insights</span>
        </>
      )}
    </motion.button>
  )
}

export default ExportButton

